### ISSUE TITLE
Adding Intergration Error

### ISSUE THREAD

**Issue by Chrisbrown01942** [nathanmarlor/foxess_modbus#10]
Hi Nathan, followed the usual HACS procedure to download foxess_modbus, and all is fine. But when I try to add the integration I receive an error & can not add it.

![Screenshot 2023-03-08 180335](https://user-images.githubusercontent.com/118054494/223794162-4860a937-4052-445c-be88-de26167f6230.jpg)
![Screenshot 2023-03-08 180314](https://user-images.githubusercontent.com/118054494/223794165-8a3b9139-9d6f-4ddc-9807-06d924541d90.jpg)
 

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by nathanmarlor** [comment]
Can you add some logs please?

**Comment by nathanmarlor** [comment]
Can you add some logs please?

**Comment by Chrisbrown01942** [comment]
To enable a logger is it as simple as adding the below?
# Example configuration.yaml entry
logger:

**Comment by nathanmarlor** [comment]
Can you add some logs please?

**Comment by nathanmarlor** [comment]
If it's failing to setup there should be something significant in the system -> logs.

**Comment by Chrisbrown01942** [comment]
ok got it
Logger: homeassistant.config_entries
Source: config_entries.py:834
First occurred: 18:24:06 (2 occurrences)
Last logged: 18:24:06

Error occurred loading configuration flow for integration foxess_modbus: cannot import name 'ModbusTcpClient' from 'pymodbus.client' (/usr/local/lib/python3.10/site-packages/pymodbus/client/__init__.py)

**Comment by nathanmarlor** [comment]
What version of HA are you using please? Did you restart after adding the component through HACS?

**Comment by Chrisbrown01942** [comment]
Home Assistant 2022.12.7
Supervisor 2023.03.1
Operating System 9.4
Frontend 20221213.1 - latest

Yes, I restarted HA after downloading via HACS

**Comment by nathanmarlor** [comment]
I might have overlooked something silly.

Can you try -> https://github.com/nathanmarlor/foxess_modbus/releases/tag/v1.0.1 please?

**Comment by Chrisbrown01942** [comment]
Sorry, didn't work. I've added the new log for the issue.

Logger: homeassistant.config_entries
Source: config_entries.py:834
First occurred: 18:48:48 (1 occurrences)
Last logged: 18:48:48

Error occurred loading configuration flow for integration foxess_modbus: cannot import name 'ModbusTcpClient' from 'pymodbus.client' (/usr/local/lib/python3.10/site-packages/pymodbus/client/__init__.py)

**Comment by Chrisbrown01942** [comment]
I do have a HA core & OS update avaible. Should I do that and get back to you?

**Comment by nathanmarlor** [comment]
Yes please!

**Comment by nathanmarlor** [comment]
Also worth trying v1.0.3 - I think it's related to an out of date pymodbus version in your HA. (ex: https://github.com/binsentsu/home-assistant-solaredge-modbus/issues/143)

**Comment by Chrisbrown01942** [comment]
Tried v1.0.3 same issue. I'll update HA & get back to you.

Logger: homeassistant.config_entries
Source: config_entries.py:834
First occurred: 19:34:25 (1 occurrences)
Last logged: 19:34:25

Error occurred loading configuration flow for integration foxess_modbus: cannot import name 'ModbusTcpClient' from 'pymodbus.client' (/usr/local/lib/python3.10/site-packages/pymodbus/client/__init__.py)

**Comment by Chrisbrown01942** [comment]
Updated HA to the latest version & now have it configured & working
Home Assistant 2023.3.2
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230306.0 - latest

**Comment by nathanmarlor** [comment]
Wahhhooo! :D
