### ISSUE TITLE
More validation issues

### ISSUE THREAD

**Issue by FozzieUK** [nathanmarlor/foxess_modbus#115]
I just noticed my pv2 power sensor kept going unavailable - I thought it might have been comms but the rest of the sensors were fine - checked the logs and found this

![IMG_1356](https://user-images.githubusercontent.com/113460294/229898471-74bcade3-32bc-4b2e-bf60-b395567dc6b9.png)

It’s the good old slightly negative readings you sometimes get on the pv1/2 power strings but the validation (range 0) stops it working and makes it unavailable.

I’ve made a quick change in my code for the validation ranges on pv1 & 2 power (reg’s 11002 & 11005) to start range at -1 and it’s back now showing -0.001kwh
![IMG_1357](https://user-images.githubusercontent.com/113460294/229899427-9de0c605-3453-4c59-b0cf-5a3fc03ddcb0.jpeg)

I’m pretty sure these are the only PV sensors that ever go negative, can we change the validation ranges please on 11002 & 11005 to start at -1 please :smiley:

**Comment by canton7** [comment]
I get the same for battery voltage, without a battery attached. I say we remove validation on these - we're pretty sure we're interpreting the values correctly, and all we're doing is showing unavailable instead of what the inverter reports.

**Comment by FozzieUK** [comment]
@canton7 that works for me 👍
