### ISSUE TITLE
Add total PV power sensor

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#129]
### Discussed in https://github.com/nathanmarlor/foxess_modbus/discussions/128

<div type='discussions-op-text'>

<sup>Originally posted by **andrewmooreio** April  6, 2023</sup>
Hi. I've just switched from the StealthChestnut integration and have noticed there is no total power sensor for PV output. e.g. current total solar generation PV1 + PV2 in W.

I've created a template sensor for now ```{{ (states('sensor.pv1_power') | float(default=0) + states('sensor.pv2_power') | float(default=0) ) * 1 }}```, just wondering if it's possible to hard code it into the integration, as it's a really useful metric that I'm sure a lot of users would appreciate.

There may be other sensors that are provided by templates [here](https://github.com/StealthChesnut/HA-FoxESS-Modbus/blob/main/custom_components/HA-FoxESS-Modbus/configuration.yaml#L85), but the total PV power is a particularly useful one.

Cheers.</div>

-------------

We probably need a new sensor type which adds two registers together?

**Comment by nathanmarlor** [comment]
Possibly extend the functionality you just added to combine multiple registers? I'm thinking something along the lines of a flag `SUM`, `EXTEND`?

**Comment by canton7** [comment]
I think a perfect solution would be a new sensor type which takes the two *sensors* to sum as inputs, rather than working directly on the registers. That way we don't have to worry about things like the two source sensors having different scales of post-processing steps.

**Comment by canton7** [comment]
Looks like it shouldn't be too hard? `async_track_state_change_event` lets you subscribe to changes from multiple other entities. [The integration sensor](https://github.com/home-assistant/core/blob/dev/homeassistant/components/integration/sensor.py) does a bunch of stuff we should be able to just copy

**Comment by ProtoxiDe22** [comment]
Does it make sense to also have a PV power total that sums the PV1 Power Total and PV2 power total values in KWh? i'm thinking having a single sensor in the energy dashboard would make sense especially if you want to do stuff with the forecast.solar estimates, working with a single value seems easier

**Comment by canton7** [comment]
The inverter provides that already, we call it "Solar Generation Total"

**Comment by ProtoxiDe22** [comment]
Damn i missed that, thank you.
