### ISSUE TITLE
Polling settings reset after updating

### ISSUE THREAD

**Issue by screenagerbe** [nathanmarlor/foxess_modbus#160]
## Version of the custom_component

1.4.0

## Configuration

n/a

## Describe the bug

When updating from 1.4.0b7 to 1.4.0 my polling settings were reset to the default values.
Might have been on purpose, but can't remember reading it in the release notes

## Debug log

n/a

**Comment by canton7** [comment]
I don't think we've touched anything in this area between those versions...

**Comment by screenagerbe** [comment]
I feel a bit awkward, but when updating my PROD container the settings were untouched.
So don't really know what was happening, might have been a glitch in TST related to me testing the different FoxESS integrations

**Comment by canton7** [comment]
I tried to reproduce this and couldn't I'm afraid. Installed 1.4.0b7, set up a new inverter from scratch, customised the poll rate and max read, upgraded to 1.4.0, and my settings are still present (and are being used correctly).

**Comment by screenagerbe** [comment]
I'll close this, I only encountered it in my "contaminated" TST container.
and it was not reproducible, so it's probably related to my environment.

**Comment by canton7** [comment]
Cool, thanks! The config system in HA is a bit opaque, so I wouldn't be surprised if there was some hard-to-reproduce case which messed it up...
