### ISSUE TITLE
Energy Dashboard - unable to edit after automatic setup

### ISSUE THREAD

**Issue by ryaaanmorgan** [nathanmarlor/foxess_modbus#172]
![image](https://user-images.githubusercontent.com/55667216/233773422-d2b95b12-11ed-4af0-8884-0c6df86a62e7.png)

After setting up the energy dashboard automatically through the integration, it appears you can no longer make any changes to it. 

In my case, I tried to add the solcast forecast into the PV production bit and it wouldn't allow it. 

Nath has pointed me in the direction of being able to reset it manually but might be worth considering how to do this automatically?

Thanks for all the hard work on this integration.

**Comment by canton7** [comment]
The image is a bit too compressed to see -- does that say "Unknown error" at the top?

**Comment by canton7** [comment]
So, I think the workaround is to click the "Edit" button on "Grid Consumption Total", then click "Save". 

It looks like the energy dashboard stuff is expecting us to have set `entity_energy_price` (which we never did), and it's falling over because of it. Editing/saving "Grid Consumption Total" fixes this.

I'll look at getting this fix in automatically.

**Comment by canton7** [comment]
That said, the docs for `entity_energy_price` imply it doesn't have to be set...

**Comment by canton7** [comment]
Ah right, but the energy prefs stuff uses TypedDict, and there's a difference between leaving a field unset and explicitly setting it to None, and HA is assuming we've done the latter. I think this is fixable in a migration though. I'm going to get #115 in quickly first, then add this on top.

**Comment by canton7** [comment]
That should be fixed in the latest beta, [v1.4.1b1](https://github.com/nathanmarlor/foxess_modbus/releases/tag/v1.4.1b1). Just upgrading should be enough to fix it -- you won't need to remove/re-add.

Please let me know if it doesn't work for you.

**Comment by ryaaanmorgan** [comment]
The fix worked perfectly. Thank you!!!!
