### ISSUE TITLE
Read software versions / serial number on startup?

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#176]
Not sure whether we need to / where we'd display them.... I don't really want to poll them all the time, as they're unlikely to change.

**Comment by canton7** [comment]
See https://github.com/TonyM1958/HA-FoxESS-Modbus/issues/5

**Comment by TonyM1958** [comment]
for what it's worth, I added scan_interval_static for loading model number, serial number, inverter firmware versions and battery firmware version info to my secrets and set this to 3600 so they just get scanned once an hour. Thought this was a compromise that would load the values at startup and not put a significant on-going load on the system but reflect changes in versions.

**Comment by canton7** [comment]
We now read software versions on start-up.
