### ISSUE TITLE
Add support for AIO-H3

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#239]
![image](https://github.com/nathanmarlor/foxess_modbus/assets/568104/5daebacd-d15a-4b4b-aa65-407f30e49d39)

**Comment by canton7** [comment]
Amazing, thank you! I was worried we might have our first ambiguous model prefixes, but looks like we'll be OK

**Comment by davidvalasek** [comment]
Sensors are working AIO-H3-10.0 💯

Is there possibility to get working other features like work mode, charge periods, etc?

Thank you in advance!

**Comment by canton7** [comment]
Thanks!

Noone's found registers for those yet: as far as the information I have goes (which comes from StealthChesnut's integration), the H3 only exposes holding registers in the range 3xxxx, even when connecting directly over RS485.

Now, it might be that it exposes some input registers as well. Try using modpoll to look for input registers in the range 40xxx - that's where the charge period registers for the H1 are.

**Comment by davidvalasek** [comment]
I will try modpoll, but we have last FW update 09/22 for AIO inverters. So I think its as you said, AIO is not supported for input registers. Thx for your quick replies and time. ;)

**Comment by canton7** [comment]
I wouldn't have thought much will have changed in a firmware update. Chances are noone's been looking for those registers yet (and I've only got a H1, so I'm not much use!)
