### ISSUE TITLE
Expose current inverter work mode to Home Assistant as sensor over ethernet

### ISSUE THREAD

**Issue by stevetrease** [nathanmarlor/foxess_modbus#261]
I'm using a direct ethernet connection (readonly) to my inverter to view inverter data over modbus. Works well and does just what I need it to.

I understand that I cannot set the inverter work mode via direct ethernet which is fine - I'm currently doing that manually via the FoxESS Cloud.

However, it would be very useful to see the currently set inverter work mode in Home Assistant. Essentially a Home Assistant sensor containing the current mode. 

Assuming it is possible to get the current work mode from the inverter over a direct ethernet connection would it be possible expose this as a sensor?

**Comment by canton7** [comment]
I'm afraid the work mode register simply isn't exposed over a direct ethernet connection. We can't read it or write it. I recommend switching to RS485.
