### ISSUE TITLE
H1 State Sensor

### ISSUE THREAD

**Issue by gjhill6100** [nathanmarlor/foxess_modbus#264]
Would it be possible to include the inverter State sensor ?

It would then be good to be able to use email notifications if the Inverter goes into particular states that need attention.

The other week, the main MCB for the Inverter tripped but this was not spotted for quite a while as the system does not automatically send any notifications of any system faults.

We could then maybe use the State sensor to generate some HA notifications.

**Comment by canton7** [comment]
Yep, this is next on my list!

The only thing I'm a bit nervous about is that actually reading the fault code requires an 8-register read, which is going to add quite a bit of time to anyone using a W610 over TCP

**Comment by calum-mcfarlane** [comment]
Can't help feeling that you're eventually going to have to add a disclaimer to the integration saying "The W610 isn't great, honestly" and setting the read frequency to 15 seconds or whatever.

**Comment by gjhill6100** [comment]
Hi,

Is this all implemented in a new HACS version ?

Kind Regards

Graham

**Comment by canton7** [comment]
It's out in the pre-release version v1.5.3b3
