### ISSUE TITLE
Get us included in the hacs registry

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#309]
This should make life a bit easier for people

**Comment by nathanmarlor** [comment]
Done! 🙂

**Comment by canton7** [comment]
Just making sure you don't have any objection to getting us in the default HACS registry?

**Comment by canton7** [comment]
Ah, looks lik you have to be the one to submit: https://hacs.xyz/docs/publish/include#check-owner

**Comment by nathanmarlor** [comment]
No problem, I'll do it first thing tomorrow 👍

**Comment by canton7** [comment]
Thanks!

**Comment by nathanmarlor** [comment]
@canton7 https://github.com/hacs/default/pull/1934

:)

**Comment by canton7** [comment]
Awesome thanks! Looks like they're running at least a month behind, so now we wait

**Comment by canton7** [comment]
@nathanmarlor Did you intend to add this commit? https://github.com/hacs/default/pull/1934/commits

**Comment by nathanmarlor** [comment]
@canton7 it was an auto GitHub update against main thing - I'm only on my phone though, has it done something weird? Just checking in to see how if they'd merged us into HACS yet.

**Comment by canton7** [comment]
It just wasn't clear what it was or why it was there. We seem to get one shot at being merged before they go AWOL for another few months, so I'm just a little concerned about anything wjodh might raise a question/comment, rather than an insta-merge

**Comment by nathanmarlor** [comment]
@canton7 

![Screenshot_20230921-202556~2.png](https://github.com/nathanmarlor/foxess_modbus/assets/3436911/6d31b060-6d7b-4d5d-902a-4e2e38167394)

😁😁😁😁😁

**Comment by canton7** [comment]
Yaaaaaay! I've got some time tomorrow, will try and fix the two latest issues and update the readme.
