### ISSUE TITLE
Bug in UI for new number entities

### ISSUE THREAD

**Issue by Ndrinta** [nathanmarlor/foxess_modbus#330]
Hi, running v1.6.1 here.

I was switching to it from my previous custom implementation and I noticed that `number.max_charge_current` and `number.max_discharge_current` won't (happily) accept numbers with decimal part, from the user interface at least. It throws a warning but, if you force it, it'll work.

![image](https://github.com/nathanmarlor/foxess_modbus/assets/4704172/48130f17-769c-497d-9150-d2adc568efed)

**Comment by canton7** [comment]
Thanks! Looks like `native_step` is wrong there
