### ISSUE TITLE
Load power or math issue 

### ISSUE THREAD

**Issue by zaapp** [nathanmarlor/foxess_modbus#371]
I wonder why the Load Power R/S/T entities have stopped working. They worked for the first two days of using the integration.
To illustrate the situation:
Row one -> Grid consumption
Row two -> Feed-in
Row three -> Inverter power
Row four -> Load (doesn't work, doesn't agree with what I feed into the grid and the inverter production.
Fifth row -> From battery
![image](https://github.com/nathanmarlor/foxess_modbus/assets/22096395/779cd494-c76c-487c-a6db-d6d2be4c8068)

Inverter H3-10 with Mira HV 25 battery pack (4x)
W610 RS485<>Ethernet converter

**Comment by canton7** [comment]
Looks like it might be the same as #362. 

We haven't changed anything on our side, and indeed these registers are read directly from the inverter with no calculations involved.

I wonder whether there's been a firmware update recently which broke them...

**Comment by zaapp** [comment]
It is likely that Chint DTSU666 is to blame for this situation. After switching off the mains power the unit rebooted and now the energy reading is correct.

**Comment by canton7** [comment]
Aha good to know thanks! I'll close this off. If you see a repeat, please add to #362.
