### ISSUE TITLE
Please remove requirement that end time is before start time - Fox have fixed/removed this

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#414]
### Discussed in https://github.com/nathanmarlor/foxess_modbus/discussions/413

<div type='discussions-op-text'>

<sup>Originally posted by **iancg** September 12, 2023</sup>
Hi,

Please see:

https://www.facebook.com/groups/foxessownersgroup/posts/1923430298039143/?comment_id=1923434278038745&reply_comment_id=1924573837924789

I've tested this and with software Master 1.60/Manager 1.63, using start=23:30 and end=05:30 worked as expected.

Can the check that prevents start > end be removed please.

Setting on web UI:

![image](https://github.com/nathanmarlor/foxess_modbus/assets/1828481/3445bfad-8723-470b-b421-3da0d165af37)

Battery charged overnight (it was full just before 3am, but started at 11:30 and continued over midnight and didn't start discharging until 5:30am).

![image](https://github.com/nathanmarlor/foxess_modbus/assets/1828481/c43bf310-a8cf-47af-a31d-7f29797a744b)
</div>

**Comment by lamixer** [comment]
I'd like to figure out how to set this in the HA integration at all! I can't spot what entity it is.

**Comment by canton7** [comment]
There's a service you can call, or you can use the charge period card linked from the readme.

**Comment by lamixer** [comment]
Thanks canton7 -- I missed that. I'm trying to get the card to work, isn't quite yet though! I started a discussion.
