### ISSUE TITLE
Fix "KH-" prefix detection for KH series

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#506]
Add support for the FoxESS KH 10.5 series, which currently appears to be unsupported.

![image](https://github.com/nathanmarlor/foxess_modbus/assets/6324545/e17dfb62-efe1-4d38-aa57-3352a0c0c4ab)

_Originally posted by @williamjeccles in https://github.com/nathanmarlor/foxess_modbus/discussions/505_

**Comment by williamjeccles** [comment]
@canton7 I can now install the integration and link it to the USR-W610 but all the values are coming back unavailable
![image](https://github.com/nathanmarlor/foxess_modbus/assets/6324545/b3778ef2-1915-4603-b098-58dec6060f81)

**Comment by canton7** [comment]
Check the log (Settings - System - Logs). That normally means we're unable to talk to the adapter.

**Comment by canton7** [comment]
I'm going to merge this. Feel free to hope back to #505 for help debugging your connection issues.
