### ISSUE TITLE
Poll versions on (re-)connection

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#509]
It would be nice to get the versions of firmwares of the system as sensors in Homassistant.

The updates on my system are done by foxess or my electrician. So I do not know if a new firmware arrives. With the sensor it is possible to show and alert on change.

_Originally posted by @abuesen in https://github.com/nathanmarlor/foxess_modbus/discussions/504_

**Comment by abuesen** [comment]
Thank you, inatelled beta: Looks all right, nice mdi!

I'm exited to see the first update.

**Comment by lamixer** [comment]
Hello... KH10.5 user here. Running integration version 1.10.1 and I just noticed the three entities to display inverter firmware versions (like `sensor.foxess_manager_version`). I added these to a dashboard and they are there and say have been updated between 5 and 10 minutes ago, but the version numbers displayed do not match my inverter's real version numbers. For example, I'm running 1.19 of Manager but integration says I'm running 2.81. Not sure if I missed a memo or if that means it's not working on KH. Not a top priority! Thanks.

**Comment by canton7** [comment]
@lamixer Thanks. Can you post your actual manager/master/slave versions, and the ones reported by this integration?

**Comment by lamixer** [comment]
Sure... 

Actual:
Master 1.27 / Slave 1.01 / Manager 1.19

Integration:
Master: 2.95 / Slave 2.57 / Manager 2.81

**Comment by abuesen** [comment]
I'm sorry I didn't remember the foxess-cloud at all since I use the great foxess-modbus integration. So my reported versions in other discussions are wrong. 

foxess-cloud says: Master : 1.83 Slave : 1.03 Manager : 1.66
foxess-modbus syas: Master : 1.83 Slave : 1.03 Manager : 3.85
Hardware: Master : 1.83 Slave : 1.03 Manager : 1.66
