### ISSUE TITLE
Detected that custom integration 'foxess_modbus' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9

### ISSUE THREAD

**Issue by Vato9394** [nathanmarlor/foxess_modbus#562]
## Version
Integration version: V1.10.1
Home assistant version: 2024.3

## Describe the bug

It is working for now, but hass.components.websocket_api will be deprecated in Home assistant 2024.9

## Debug log

```text

Detected that custom integration 'foxess_modbus' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9

```

**Comment by canton7** [comment]
https://developers.home-assistant.io/blog/2024/02/27/deprecate-bind-hass-and-hass-components
