### ISSUE TITLE
Warning message about deprecated accesses to hass.components.websocket_api

### ISSUE THREAD

**Issue by Ric57100** [nathanmarlor/foxess_modbus#563]
Hi,

I was browsing my homeassistant log file when I came across this message :

2024-03-07 15:23:03.554 WARNING (MainThread) [homeassistant.helpers.frame]
Detected that custom integration 'foxess_modbus' accesses hass.components.websocket_api. **This is deprecated and will stop working in Home Assistant 2024.9**, it should be updated to import functions used from websocket_api directly at custom_components/foxess_modbus/services/websocket_api.py, line 16: hass.components.websocket_api.async_register_command(get_charge_periods), please create a bug report at https://github.com/nathanmarlor/foxess_modbus/issues

I am currently using the latest version of this integration with HAOS 2024.3.0  so I think everyone should have it in their log file.

Regards

**Comment by canton7** [comment]
Thanks! Closing as a dup of #562
