### ISSUE TITLE
Load sensor artificially low after latest beta release.

### ISSUE THREAD

**Issue by ryaaanmorgan** [nathanmarlor/foxess_modbus#571]
Evening lads, noticed my "load" sensor hit rock bottom despite all other sensors (including the CT) being correct.
I've done some digging and really can't explain it. It's not done wonders for my losses sensor 🤣

Any thoughts? It coincided with the upgrade to the latest beta last night and I think that might be a bug.
Nothing in the logs to suggest an issue neither.

![image](https://github.com/nathanmarlor/foxess_modbus/assets/55667216/c668d6e9-2140-4400-bb96-8502af4f5903)

**Comment by ryaaanmorgan** [comment]
HA is at version 2024.3.0

**Comment by ryaaanmorgan** [comment]
I've moved back to the most recent non-beta release and the load sensor is fixed.
Any details you need to help recreate the error - let me know.

**Comment by FozzieUK** [comment]
Morning Ryan, thanks for spotting that :)

@canton7 - looks like an error crept in when refactoring - see https://github.com/nathanmarlor/foxess_modbus/pull/572
