### ISSUE TITLE
Beta v1.10.2b3 "breaks" battery charge entity

### ISSUE THREAD

**Issue by jaal2001** [nathanmarlor/foxess_modbus#573]
Before installing v1.10.2b3 the battery charge reporting was working without a hassle.

After installing v1.10.2b3 I've noticed the missing battery charge indicator. Battery charge today still increases but the inverter_battery_charge is stuck.
Going back to v1.10.2b2 solved that problem.

H3-10 installed.

**Comment by FozzieUK** [comment]
ok thanks for that, resolved in https://github.com/nathanmarlor/foxess_modbus/pull/574 and should be corrected in next release
@canton7 fyi

**Comment by canton7** [comment]
Thanks! That'll be fixed in the next beta.
