### ISSUE TITLE
Add H3 Inverter Sensors

### ISSUE THREAD

**Issue by nathanmarlor** [nathanmarlor/foxess_modbus#6]

**Comment by benbeton** [comment]
I'm happy to help, let me know what you need for the H3 inverter support

**Comment by nathanmarlor** [comment]
Thanks @benbeton 

Basically need one of these creating for H3 aux and LAN -> https://github.com/nathanmarlor/foxess_modbus/blob/main/custom_components/foxess_modbus/sensors/h1_aux_sensors.py

I can do the rest :)

**Comment by canton7** [comment]
Permalink: https://github.com/nathanmarlor/foxess_modbus/blob/b519e72318512df877490320232e1f1a354a5e20/custom_components/foxess_modbus/entities/xx1_aux_sensors.py

**Comment by benbeton** [comment]
created the first sensors: https://github.com/nathanmarlor/foxess_modbus/pull/57
Source for H3 Sensors: https://github.com/rsaemann/HA-FoxESS-H3-Modbus/blob/main/custom_components/HA-FoxESS-Modbus/modbusLAN-H3.yaml

**Comment by canton7** [comment]
Fixed in #167
