### ISSUE TITLE
Are Ambient Temp and Inverter Temp correct registers

### ISSUE THREAD

**Issue by Stephens-ely** [nathanmarlor/foxess_modbus#61]
When comparing the registers used for this FoxESS modbus integration I've noticed that the registers used for Ambient Temp and Inverter Temp are revered when compared to the integration offered by StealthChesnut.

I'm not in a position to say which is correct so am just pointing out the difference;

In https://github.com/StealthChesnut/HA-FoxESS-Modbus/wiki/Data-Register-Reference---H1-AC1

11024 = InvTemperation
11025 = AmbientTemperature

In this integration as defined in xx1_aux_sensors.py

    SensorDescription(
        key="invtemp",
        address=11025,
        name="Inverter Temp",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°C",
        scale=0.1,
    ),
    SensorDescription(
        key="ambtemp",
        address=11024,
        name="Ambient Temp",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement="°C",
        scale=0.1,
    ),

These are for the USR/USB connection

**Comment by nathanmarlor** [comment]
Good spot, checked against Fox Cloud and fixed in #68

**Comment by Ndrinta** [comment]
If so, please fix it in `xx1_lan_sensors.py` if necessary.
Thanks

**Comment by nathanmarlor** [comment]
@Ndrinta can you confirm the values are switched vs. fox cloud on LAN please? My LAN isn't plugged in anymore.

**Comment by Ndrinta** [comment]
They are indeed.

![image](https://user-images.githubusercontent.com/4704172/226997428-cc292998-9a11-4ff7-9c49-158f66b8e2cb.png)
![image](https://user-images.githubusercontent.com/4704172/226997540-b754c009-0d6e-4b09-b254-227d1840c06d.png)
