### ISSUE TITLE
Sensor name misleading for BMS kW Remaining

### ISSUE THREAD

**Issue by Stephens-ely** [nathanmarlor/foxess_modbus#62]
In xx1_aux_sensors.py

The sensor with name 'bms_kwh_remaining' has a Friendly description of "BMS kW Remaining".

    SensorDescription(
        key="bms_kwh_remaining",
        address=11037,
        name="BMS kW Remaining",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        native_unit_of_measurement="kWh",
        scale=0.01,
    ),

Should the name not be "BMS kWh Remaining" ?

**Comment by nathanmarlor** [comment]
Thanks, fixed in #64
