### ISSUE TITLE
Investigate larger reads with the W610

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#66]
I'm [playing around with modpoll](https://github.com/StealthChesnut/HA-FoxESS-Modbus/wiki/USR-W610-Setup-Guide#troubleshooting-usr) and the W610, and I can fairly reliably perform large (>50 register) reads, provided that I pick the right registers.

E.g. I can poll 76 registers starting at 11020, but only a 75-register read from 11021. I can't read 11096 at all, even with a 1-register read.

So, I'm beginning to suspect that the issue is that some registers just aren't readable. With a larger read window, we were happening to hit registers which aren't readable.

This needs some more testing, but I think we could probably hugely increase the read size if we're careful to avoid unreadable registers. Probably best implemented with a whitelist of registers which are known to be safe to read.

**Comment by nathanmarlor** [comment]
Interesting - on the W610 I can't read > 10 reliably.

![image](https://user-images.githubusercontent.com/3436911/226927035-46cf6083-adac-4cf7-bfcc-24713753fec5.png)

![image](https://user-images.githubusercontent.com/3436911/226927103-dde08617-cb0d-4296-a759-3b5898f1d169.png)

**Comment by canton7** [comment]
Turns out this is specific to the Windows version of modpoll. When the W610 returns an incomplete frame, as it does if you try and read more than 8 registers, the Windows modpoll just shows garbage. The Linux version at least shows 0's (and pymodpoll throws an error).

So, I was being fooled by what is presumably uninitialized memory somewhere... Oh well.
