### ISSUE TITLE
Added sensor

### ISSUE THREAD

**Issue by manuele84** [nathanmarlor/foxess_modbus#70]
Congratulations for the project, is it possible to add the following sensor?

Ind: 11011		exit inverter

and a sensor that indicates the alarm status of the inverter.

**Comment by nathanmarlor** [comment]
@manuele84 can you add a little more description of what this sensor is/does please? :)

**Comment by nathanmarlor** [comment]
@manuele84 :)

**Comment by manuele84** [comment]
> @manuele84 :)
Sorry for the delay, the sensor calculates the power that comes out of the inverter in kw.

```
    - name: "Exit inverter"
      scan_interval: 5
      slave: 247
      address: 11011
      state_class: measurement
      unit_of_measurement: "kW"
      data_type: int16
      scale: 0.001
      precision: 3
      input_type: input
      device_class: power

```

**Comment by nathanmarlor** [comment]
@manuele84 thank you, will add it in asap 😊

**Comment by canton7** [comment]
(or rename the yield ones to this)

**Comment by canton7** [comment]
Looking more, the numbers are identical to Feed-In. Which makes sense: the foxess app calls this RPower, and that makes sense as the register is right next to RVolt.

So we've just found another way of fetching Feed-in, which we were getting from the Grid CT anywya.

**Comment by canton7** [comment]
Although, coming back to it this afternoon, and the values of 11011 aren't matching feed-in any more.

**Comment by manuele84** [comment]
![Screenshot_2023-03-25-19-15-04-30_8e6f52239f4dc04be92d9657a7249325](https://user-images.githubusercontent.com/63157208/227734601-c8532687-6016-4d1c-9df6-6980b186e48a.jpg)

11011 is the Power exit inverter

**Comment by nathanmarlor** [comment]
Joining the pieces up - I'm guessing the 'inverter power' (or whatever we call it) matches feed in if you don't have batteries and PV isn't yet generating as it's AC -> AC. The difference between this and feed-in will be inverter efficiency losses due to the DC -> AC conversion. Makes sense?

**Comment by nathanmarlor** [comment]
Thanks @manuele84 - you put me on the right path to rationalising all the battery/inverter sensors. Now added in #101
